# Generated by Django 5.1.3 on 2025-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field2Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Field 2 Name',
                'verbose_name_plural': 'Field 2 Names',
                'db_table': 'field_2_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=45, null=True)),
                ('field_2', models.CharField(blank=True, max_length=45, null=True)),
                ('field_3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Field Name',
                'verbose_name_plural': 'Field Names',
                'db_table': 'field_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.FloatField()),
                ('field_3', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Field Value',
                'verbose_name_plural': 'Field Values',
                'db_table': 'field_values',
                'ordering': ['-field_3'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Record Name',
                'verbose_name_plural': 'Records Names',
                'db_table': 'records_name',
                'managed': False,
            },
        ),
    ]
